import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}

export const preferredIndustries = [
	"A/B Testing",
	"Accounting & Audit",
	"Adaptability",
	"Agriculture & Agribusiness",
	"Agritech",
	"AI & Data Science",
	"Analytical Thinking",
	"Apollo",
	"Art & Culture",
	"Automotive",
	"Banking",
	"Beauty & Personal Care",
	"Branding & Creative Agencies",
	"Business Support Services",
	"Climate Tech / CleanTech",
	"Cold Calling",
	"Cold Emailing",
	"Collaboration",
	"Community & Religious Organizations",
	"Competitor Analysis",
	"Construction",
	"Consulting & Advisory",
	"Content Marketing",
	"Conversion Rate Optimization (CRO)",
	"Creativity",
	"CRM Management",
	"Critical Thinking",
	"Cybersecurity",
	"Decision Making",
	"Deal Structuring",
	"Delivery & Couriers",
	"Digital Marketing",
	"Digital Media",
	"Diagnostics & Labs",
	"Ecommerce",
	"Edtech",
	"Email Marketing",
	"Emotional Intelligence",
	"Energy & Utilities",
	"Environmental Services",
	"Events & Entertainment",
	"Fashion & Apparel",
	"Film & TV Production",
	"Fintech",
	"Fitness & Wellness",
	"FMCG",
	"Food & Beverage",
	"Food Services / Restaurants",
	"Funnel Building",
	"Gaming & Animation",
	"Go-To-Market Strategy (GTM)",
	"Growth Experimentation",
	"Growth Loops",
	"Hardware & IoT",
	"Healthtech",
	"Hospitals & Clinics",
	"Hospitality Tech",
	"Hotels & Hospitality",
	"HR & Recruitment Services",
	"HR Tech",
	"HubSpot",
	"Influencer & Creator Economy",
	"Infrastructure Development",
	"Insurtech",
	"Insurance",
	"Internet Service Providers (ISPs)",
	"International Development",
	"Investment & Asset Management",
	"Lead Generation",
	"Leadership",
	"Legal Services",
	"Legaltech",
	"Lifestyle & Consumer Goods",
	"Logistics & Supply Chain",
	"Logistics & Supply Chain Tech",
	"Manufacturing",
	"Martech",
	"Marketing & Advertising Agencies",
	"Media & Entertainment",
	"Mental Health Services",
	"Microfinance",
	"Mining",
	"Mobility & Transport Tech",
	"Negotiation",
	"Nonprofits & NGOs",
	"Objection Handling",
	"Oil & Gas",
	"Online Learning Platforms",
	"Outreach",
	"Paid Ads Management",
	"Partnership Development",
	"Partnership Management",
	"Partnership Negotiation",
	"Pharmaceuticals",
	"Pipedrive",
	"Pitching & Demo Delivery",
	"Private Equity & Venture Capital",
	"Problem Solving",
	"Procurement",
	"Product Positioning",
	"Product-Led Growth (PLG)",
	"Professional Training",
	"Proptech / Real Estate Tech",
	"Proptech Platforms",
	"Proposal Writing",
	"Public Relations",
	"Public Sector",
	"Publishing",
	"Real Estate Development",
	"Relationship Building",
	"Relationship Management",
	"Renewal Management",
	"Reporting & Analytics",
	"Research & Development",
	"Retail & Wholesale",
	"Sales Closing",
	"Sales Forecasting",
	"Sales Process Optimization",
	"Sales Prospecting",
	"Schools",
	"SEO",
	"Skills Development",
	"Social Enterprises",
	"Social Media Management",
	"Software & SaaS",
	"Sports",
	"Stakeholder Management",
	"Strategic Alliances",
	"Telecommunications",
	"Telemedicine",
	"Time Management",
	"Training & Professional Development",
	"Transportation",
	"Universities & Colleges",
	"Upselling",
	"User Acquisition",
	"User Engagement",
	"User Retention Strategy",
	"Value Proposition Design",
	"Vocational Training",
	"Warehousing",
	"Waste & Recycling",
	"Water & Waste Management",
	"Workflow Automation",
	"Zoho CRM",
];
